### ISSUE TITLE
ability to cancel adding a tree

### ISSUE THREAD

**Issue by durkie** [PublicDesignWorkshop/FoodParent2.0#14]
once you click the ➕  icon there's not really a way to get out of that right now.

**Comment by ThePlushEater** [comment]
There is a bug, and I am fixing it, but still you can escape the add mode by clicking a back button. Or do you want me to create a cancel button? That might solve the bug together since the bug happens when the users click the back button. There is a data sync issue when users click the back button.

**Comment by durkie** [comment]
a cancel button would be good also to keep the UI consistent -- there are ✖️  symbols on most other parts of the app.
