### ISSUE TITLE
Apply CSS to flagged trees

### ISSUE THREAD

**Issue by durkie** [PublicDesignWorkshop/FoodParent2.0#2]
How about creating a "style" field in the `flag` table that gets applied to the icon of all trees with that flag? Hidden trees should actually be hidden, for instance, and maybe verified trees have a red outline or something.

**Comment by ThePlushEater** [comment]
From your e-mail:
- Would it be possible to attach some sort of css style to a flag? Like if the tree has the "hidden" flag, apply "opacity: 0.8;" to that tree's marker. And if the tree has the "dead" flag, apply "transform: scale(0.5,0.5);" to the icon. Something like that. That way we can visually differentiate dead/hidden trees (and for future flags too).

**Comment by ThePlushEater** [comment]
I like the idea of using css style, and it is not hard thing to do. Along with different css styles for markers, we also need to think about the style of actual food markers. Do you like current style of tree markers? If we use svg markers, we can actually override colors of svg markers, such as coloring them as black for trees which are dead.

**Comment by ThePlushEater** [comment]
I added the `classname` field in flag `table`.
![foodparent_flag_table](https://cloud.githubusercontent.com/assets/10521601/15995244/e2d7183e-30e5-11e6-9cee-d27dd380f3e5.PNG)

I tried to use transform: scale(0.5, 0.5) value, it conflict with tranform css value is already used by leaflet. Thus, instead of using tranform css style, I used "filter css tyle". Options can be found in http://www.w3schools.com/cssref/playit.asp?filename=playcss_filter&preval=blur(5px)

And the classnames for the flag styles are defined in **{app-root-directory}/src/client.css**
The CSS styles for flagged icons are defined in **{app-root-foler}/src/client.css**.

Hidden flag example: http://foodparent.thecaptainwhale.com/tree/723
Dead flag example: http://foodparent.thecaptainwhale.com/tree/47
- You need to login as manager or admin account to find these trees.
