### ISSUE TITLE
Include filter for a tree in url routing.

### ISSUE THREAD

**Issue by ThePlushEater** [PublicDesignWorkshop/FoodParent2.0#7]
If the url holds the tree item id, like {app-address}/trees/142 (142 is the tree id), it need to show the item on the map. However, for now, the marker doesn't appear if the item is not matched to the filter. To fix this, I need to include the food type of the tree item of url (not in*) automatically when the map is loaded.

**Comment by durkie** [comment]
This doesn't feel like the right solution to me -- maybe I'm misunderstanding something, but at the very least it seems like redundant information. If you're including it in the URL, then it seems like the purpose of that it to tell the server something: "We want to see tree 142, which is a blueberry", but the server will already know this because it can just look up tree 142 and figure out what type it is.

Also, if tree 142 is a blueberry, what happens if I request `/trees/Apples/142` instead of `/trees/Blueberries/142`?

Why does it need to appear in the url?

**Comment by ThePlushEater** [comment]
Sorry, my wording was totally incorrect. I just want to add type of food into the filter list, not inside of url. I will not change the structure of url, just as we talked last week, if 142 is an apple tree, and if apple is not current seasonal fruits, I add apple into the filter list so that apple + other seasonal fruits will appear together.

**Comment by durkie** [comment]
👍

**Comment by ThePlushEater** [comment]
Fixed.
